on:
  issue_comment:
    types:
      - created
jobs:
  container-tests:
    uses: "pkhartsk/.github/.github/workflows/container-tests.yml@main"
    with:
      version: "['2.4', '2.4-micro']"
    secrets: inherit
